config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index]
  resources :tasks, only: [:create, :destroy]
  resources :lists, only: [:index, :create, :destroy]
  
  get 'send_friend_request', to: 'users#send_friend_request'
  get 'accept_friend_request', to: 'users#accept_friend_request'
  get 'decline_friend_request', to: 'users#decline_friend_request'
  get 'unfriend', to: 'users#unfriend'
  
  authenticated :user do
    root :to => 'users#show', :as => :authenticated_root
  end

  root 'welcome#landing'

  get 'welcome/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :tasks, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_friendship
  
  before_save :update_email_name
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  validates_format_of :username, with: /^[a-z0-9_\.]*$/, :multiline => true, :message => "is invalid. Make sure you have no uppercase letters!"
  validate :validate_username
  validates :username, length: {minimum: 5, maximum: 20 }, presence: true 

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
 
  # overwrites devise's default <find_for_database_authentication> to include username 
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["username = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end
  
  def update_email_name
    self.email_name = "#{self.email.split('@').first}"
  end
  
  # gives this model search functionality
  def self.search(search)
    where("username LIKE ? OR email_name LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_body_class, only: [:index]
  
  def index
    @friends = User.all.map { |user| user != current_user && associated_with(user) ? user : nil }.compact
    
    if params[:search].present? && params[:search].length >= 3
      @searched_users = User.search(params[:search]).map { |user| user == current_user || associated_with(user) ? nil : user }.compact

      if @searched_users
        flash.now[:notice] = "Showing #{@searched_users.count} #{"result".pluralize(@searched_users.count)} for \" #{params[:search]} \""
      end
    end
    
    respond_to do |format|
      format.html 
      format.js
    end
  end
  
  def show
    @task = Task.new
    @user = params[:id].present? ? User.find(params[:id]) : current_user

    @lists = @user.lists
    @list = params[:list_id].present? ? @lists.find(params[:list_id]) : @lists.first

    unless current_user.friends.include?(@user) || @user == current_user
      flash[:alert] = "You need to be friends to view other peoples's TO-DO lists.."
      begin
        redirect_to :back and return
      rescue
        redirect_to root_path
      end
    end
    
    @tasks = @list.tasks.unexpired
    @expired_tasks = @list.tasks.expired
  end
  
  def send_friend_request # send a request to a diff user
    current_user.friend_request(get_target_user)
    
    redirect_to users_path
  end
  
  def accept_friend_request # accept someone's request to be your friend
    current_user.accept_request(get_target_user)
    
    redirect_to users_path
  end
  
  def decline_friend_request # decline someone's request to be your friend
    current_user.decline_request(get_target_user)
    
    redirect_to users_path
  end
  
  def unfriend # remove someone from being your friend (also kills a pending request)
    current_user.remove_friend(get_target_user)
    
    redirect_to users_path
  end
  
  private
  
  def get_target_user
    @user = User.find(params[:target_user])
  end
  
  # returns true if user is not a pending/requested or friend of current_user
  def associated_with(user)
    current_user.friends.include?(user) || current_user.requested_friends.include?(user) || current_user.pending_friends.include?(user)
  end
  
  def set_body_class
    @body_class = "users"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_status.html.erb
<% if current_user.friends.include? user %>
    <%= link_to "Unfriend", unfriend_path(target_user: user) %>
<% elsif current_user.requested_friends.include? user %>
    Wants to be your friend:   
    <%= link_to "accept", accept_friend_request_path(target_user: user) %> - 
    <%= link_to "decline", decline_friend_request_path(target_user: user) %>
<% elsif current_user.pending_friends.include? user %>
    Friend requst sent! 
    <%= link_to "retract?", unfriend_path(target_user: user) %>
<% else %>
    <%= link_to "Send friend request", send_friend_request_path(target_user: user) %> 
<% end %>

app/views/users/_index.html.erb
<% users.each do |user| %>
    <% if user != current_user %>
        <tr class="user">
            <td><%= user.username %></td>
            <td>
                <% if current_user.friends.include? user %>
                    <%= link_to "Checkout To-Do", user %>
                <% end %>
            </td>
            <td><%= render partial: 'users/friend_status', locals: {user: user} %></td>
        </tr>
    <% end %>
<% end %>

app/views/users/_my_lists.html.erb
<% lists.each do |list| %>
    <% if list == current_list %>
        <div class="lists visible-list"><%= list.title %></div>
    <% else %>
        <%= link_to "#{list.title}", root_path( list_id: list, id: params[:id] ), class: "lists hidden-lists", id: "list-#{list.id}" %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h5 class="friends-heading">Manage all your Friends here</h5>

<div class="friend-search">
    <%= form_tag(users_path, method: "get", id: "search-form", remote: true) do %>
            <%= text_field_tag :search, params[:search], placeholder: "Find new friends...", class: 'form-control search-field' %>
            <%= submit_tag "search", name: nil, class: 'btn btn-default btn-sm search-submit' %>
            <%= link_to "Clear", "#", id: "clear-search", class: 'search-clear' %>
    <% end %>
</div>
<table class="table table-hover">
    <tr id="heading">
        <th class="col-md-5 peop-col-1">Friends</th>
        <th class="col-md-3 view-col-2"></th>
        <th class="col-md-4 stts-col-3">Status</th>
    </tr>
    <% if @friends.present? %>
        <% log_info @friends.length %>
        <%= render partial: 'index', locals: { users: @friends } %> 
    <% else %>
        <tr class="user">
            <td>You have no connections yet!</td>
            <td></td>
            <td></td>
        </tr>
    <% end %>
    <tbody id="search-results"></tbody>
</table>

app/views/users/index.js.erb
<% if @searched_users %>
    $('#search-results').html("<tr class='search-message'><th><%= flash.now[:notice] %></th><th></th><th></th></tr>");
    $('#search-results').append("<%= escape_javascript(render partial: 'index', locals: { users: @searched_users }) %>");
<% end %> 

app/views/users/show.html.erb
<div class="list-toggle">
    <%= render partial: 'my_lists', locals: { lists: @lists, current_list: @list } %>
</div>

<div class="expired-task-toggle">
    <%= expired_task_button %>
</div>

<table class="table table-hover">
    <tr id="heading">
        <th class="col-md-6 task-desc" id="task-count"><%= subject_parse(@user) %><%= pluralize(@tasks.count, "Task").split.insert(1, "active").join ' ' %></th>
        <th class="col-md-4 time-rema">Time remaining</th>
        <% if @user == current_user %>
            <th class="col-md-2 compl-yet">Complete?</th>
        <% end %>
    </tr>
    <tbody class="all-tasks"><%= render @tasks %></tbody>
    <tbody class="collapse" id="expired-tasks"><%= render @expired_tasks %></tbody>
    <% if @user == current_user %>
        <%= render partial: 'tasks/form', locals: { task: @task, current_list: @list } %>
    <% end %>
</table>