config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index]
  resources :tasks, only: [:create, :destroy]
  resources :lists, only: [:index, :create, :destroy]
  
  get 'send_friend_request', to: 'users#send_friend_request'
  get 'accept_friend_request', to: 'users#accept_friend_request'
  get 'decline_friend_request', to: 'users#decline_friend_request'
  get 'unfriend', to: 'users#unfriend'
  
  authenticated :user do
    root :to => 'users#show', :as => :authenticated_root
  end

  root 'welcome#landing'

  get 'welcome/about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To Do Countdown</title>
  <meta name="viewport" content="width=devise-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class %>">
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Friends", users_path %></li>
        <li><%= link_to "My Lists", lists_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
      
        <div class="user-ctrl">
          <% if user_signed_in? %>
            <h5><%= current_user.username %></h5>
            <div class="dropdown menu-icon">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
              <ul class="dropdown-menu menu-list">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
      
      <header>
        <h2>TO~DO<small>countdown</small></h2>
        <p>Your Task list decluttered.</p>
      </header>
    
      <div class="flash">
        <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      </div>
  
      <%= yield %>
      
      <!--<footer>-->
      <!--  <p>TO~DO<small>countdown</small></p>  -->
      <!--</footer>-->
</body>
</html>